version: '3.8'

services:
  application:
    image: wopr:latest
    environment:
      message.text: This message is from a Docker Compose file.
    ports:
      - 8080:8080
    depends_on:
      - database
  
  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: wopr
      POSTGRES_USER: wopr
      POSTGRES_PASSWORD: wopr
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  